// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbVzLh-5qpzHTWuZZPmiQMqBeje9av8jA',
    appId: '1:120578827237:web:158bea3c6989fdc62bc50c',
    messagingSenderId: '120578827237',
    projectId: 'magi-hair-off-app',
    authDomain: 'magi-hair-off-app.firebaseapp.com',
    storageBucket: 'magi-hair-off-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkUwioashsh3Eog2HoushoLkAdWz9Z498',
    appId: '1:120578827237:android:be5e2ca6ce4ed0582bc50c',
    messagingSenderId: '120578827237',
    projectId: 'magi-hair-off-app',
    storageBucket: 'magi-hair-off-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqX56rXvf22sFhvf9TEl9MZ4JFx-KYy7M',
    appId: '1:120578827237:ios:1864f7935c1a3ac82bc50c',
    messagingSenderId: '120578827237',
    projectId: 'magi-hair-off-app',
    storageBucket: 'magi-hair-off-app.firebasestorage.app',
    iosBundleId: 'com.magihair.magiHairOff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqX56rXvf22sFhvf9TEl9MZ4JFx-KYy7M',
    appId: '1:120578827237:ios:1864f7935c1a3ac82bc50c',
    messagingSenderId: '120578827237',
    projectId: 'magi-hair-off-app',
    storageBucket: 'magi-hair-off-app.firebasestorage.app',
    iosBundleId: 'com.magihair.magiHairOff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbVzLh-5qpzHTWuZZPmiQMqBeje9av8jA',
    appId: '1:120578827237:web:8f635338a0f1cb7e2bc50c',
    messagingSenderId: '120578827237',
    projectId: 'magi-hair-off-app',
    authDomain: 'magi-hair-off-app.firebaseapp.com',
    storageBucket: 'magi-hair-off-app.firebasestorage.app',
  );
}
